services:
  # CPU版本 - 适用于没有GPU的环境
  iopaint-cpu:
    image: kkape/iopaint:cpu
    container_name: iopaint-cpu
    ports:
      - "8080:8080"
    environment:
      # 基础配置
      - IOPAINT_HOST=0.0.0.0
      - IOPAINT_PORT=8080
      - IOPAINT_MODEL=lama                    # 可选: lama, ldm, zits, mat, fcf, manga, cv2, migan
      - IOPAINT_DEVICE=cpu
      - IOPAINT_QUALITY=95                    # 图片质量 0-100
      
      # 性能优化配置
      - IOPAINT_NO_HALF=false                # 使用全精度模型 (fp32)
      - IOPAINT_LOW_MEM=false                # 启用注意力切片和VAE平铺以节省内存
      - IOPAINT_CPU_OFFLOAD=false            # 将模型权重卸载到CPU RAM
      - IOPAINT_DISABLE_NSFW_CHECKER=false   # 禁用NSFW检查器
      
      # 可选: 输入输出目录 (需要挂载对应的卷)
      # - IOPAINT_INPUT=/app/input
      # - IOPAINT_OUTPUT_DIR=/app/output
    volumes:
      # 可选: 挂载输入输出目录
      # - ./input:/app/input
      # - ./output:/app/output
      # 模型缓存目录 (可选，用于持久化下载的模型)
      - iopaint_models:/root/.cache
    restart: unless-stopped
    profiles:
      - cpu

  # GPU版本 - 适用于有NVIDIA GPU的环境
  iopaint-gpu:
    image: kkape/iopaint:gpu
    container_name: iopaint-gpu
    ports:
      - "8080:8080"
    environment:
      # 基础配置
      - IOPAINT_HOST=0.0.0.0
      - IOPAINT_PORT=8080
      - IOPAINT_MODEL=lama                    # 可选: lama, ldm, zits, mat, fcf, manga, cv2, migan
      - IOPAINT_DEVICE=cuda
      - IOPAINT_QUALITY=95                    # 图片质量 0-100
      
      # 性能优化配置
      - IOPAINT_NO_HALF=false                # 使用全精度模型 (fp32)
      - IOPAINT_LOW_MEM=false                # 启用注意力切片和VAE平铺以节省内存
      - IOPAINT_CPU_OFFLOAD=false            # 将模型权重卸载到CPU RAM
      - IOPAINT_DISABLE_NSFW_CHECKER=false   # 禁用NSFW检查器
      
      # 可选: 输入输出目录 (需要挂载对应的卷)
      # - IOPAINT_INPUT=/app/input
      # - IOPAINT_OUTPUT_DIR=/app/output
    volumes:
      # 可选: 挂载输入输出目录
      # - ./input:/app/input
      # - ./output:/app/output
      # 模型缓存目录 (可选，用于持久化下载的模型)
      - iopaint_models:/root/.cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    profiles:
      - gpu

  # 开发版本 - 使用本地构建的镜像
  iopaint-dev:
    build:
      context: .
      dockerfile: docker/CPUDockerfile
      args:
        version: "1.3.5"  # 替换为实际版本
    container_name: iopaint-dev
    ports:
      - "8080:8080"
    environment:
      - IOPAINT_HOST=0.0.0.0
      - IOPAINT_PORT=8080
      - IOPAINT_MODEL=lama
      - IOPAINT_DEVICE=cpu
      - IOPAINT_QUALITY=95
    volumes:
      - iopaint_models:/root/.cache
    restart: unless-stopped
    profiles:
      - dev

volumes:
  iopaint_models:
    driver: local

# 网络配置 (可选)
networks:
  default:
    name: iopaint_network
